var fruits;
fruits = ['mango', 'apple', 'banana', 'pinapple'];
console.log("All fruits : " + fruits);
console.log("Fruits avail in first index : " + fruits[1]);
console.log();
console.log("Specific type of values");
var animals;
animals = ["lion", 'tiger', 'deer', 'beer'];
console.log(animals);
console.log();
console.log("mixed type of values");
var student;
student = ['akshay', 87, 'akhare', "mahaarathi", 74];
console.log(student);
console.log();
console.log("Any type of values");
var everything;
everything = ['lion', 857, true, 57.8];
console.log(everything);
